kind: pipeline
type: docker
name: notice test
trigger:
  event:
    - push
  branch:
    - main
steps:
  - name: build
    image: golang:1.18
    environment:
      GO111MODULE: "on"
    commands:
      - go get -v -t -d ./...
      - go build
  - name: notice
    image: hb0730/drone-plugin-notice:1.0.6-beta.1
    settings:
      webhook:
        from_secret: notice_webhok
      secret:
        from_secret: notice_secret
      robot_type: dingtalk
      content_type: markdown
      message_title: drone-plugin-notice 测试
      at_only_failure: true
      debug: true
      custom_started: DRONE_STAGE_STARTED
      custom_finished: DRONE_STAGE_FINISHED
      message_content: |
        ### 构建信息
        > - 应用名称: [DRONE_REPO_NAME]
        > - 构建结果: [CUSTOM_BUILD_STATUS]
        > - 构建发起: [CI_COMMIT_AUTHOR_NAME]
        > - 持续时间: [CUSTOM_BUILD_CONSUMING]s

        构建日志: [点击查看详情]([DRONE_BUILD_LINK])
    when:
      status:
        - success
        - failure

  - name: notice feishu
    image: hb0730/drone-plugin-notice:1.0.6-beta.1
    settings:
      webhook:
        from_secret: notice_feishu_webhok
      secret:
        from_secret: notice_feishu_secret
      robot_type: feishu
      content_type: markdown
      message_title: drone-plugin-notice 测试
      at_only_failure: true
      debug: true
      custom_started: DRONE_STAGE_STARTED
      custom_finished: DRONE_STAGE_FINISHED
      message_content: |
        ### 构建信息
        > - 应用名称: [DRONE_REPO_NAME]
        > - 构建结果: [CUSTOM_BUILD_STATUS]
        > - 构建发起: [CI_COMMIT_AUTHOR_NAME]
        > - 持续时间: [CUSTOM_BUILD_CONSUMING]s

        构建日志: [点击查看详情]([DRONE_BUILD_LINK])
    when:
      status:
        - success
        - failure